version: '3'

services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: .docker/dockerfile.backend
            args:
                - DATABASE_URL=${DATABASE_URL}
        environment:
            - DOCKER=true
            - NODE_ENV
            - JWT_SECRET
            - PUB_HOST
            - PUB_PORT
            - PUB_PORT_SSL
            - BACKEND_PUB_ENDPOINT
            - BACKEND_INT_PORT
    client:
        container_name: client
        build:
            context: .
            dockerfile: .docker/dockerfile.client
            args:
                - DOCKER=true
                - NODE_ENV=${NODE_ENV}
                - PUB_PORT=${PUB_PORT}
                - PUB_PORT_SSL=${PUB_PORT_SSL}
                - PUB_HOST=${PUB_HOST}
                - BACKEND_PUB_ENDPOINT=${BACKEND_PUB_ENDPOINT}
                - BACKEND_INT_PORT=${BACKEND_INT_PORT}
                - CLIENT_INT_PORT=${CLIENT_INT_PORT}
    nginx:
        container_name: gateway
        build:
            context: .
            dockerfile: .docker/dockerfile.gateway
            args:
                - PUB_HOST=${PUB_HOST}
        image: nginx
        restart: always
        depends_on:
            - client
            - backend
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./.nginx/gateway.conf.template:/etc/nginx/templates/default.conf.template
        environment:
            - PUB_PORT
            - PUB_PORT_SSL
            - BACKEND_PUB_ENDPOINT
            - BACKEND_INT_PORT
            - BACKEND_INT_ADDR
            - CLIENT_INT_PORT
            - CLIENT_INT_ADDR
