FROM node:18-bullseye AS pruner

WORKDIR /home/node

COPY . .

RUN yarn global add turbo
RUN yarn run prune -- --scope @blog/backend --out-dir dist/backend

FROM node:18-bullseye

WORKDIR /home/node

COPY --from=pruner --chown=node:node /home/node/dist/backend .

RUN yarn install

EXPOSE 5000

CMD ["yarn", "run", "service"]
